name: testing

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: install xray
        run: |
          bash <(curl -Ls https://raw.githubusercontent.com/XTLS/Xray-install/main/install-release.sh)

      - name: config client
        run: |
          cat > config.json <<EOF
          {
            "inbounds": [
              {
                "port": 1080,
                "listen": "127.0.0.1",
                "protocol": "socks"
              }
            ],
            "outbounds": [
              {
                "protocol": "vless",
                "settings": {
                  "vnext": [
                    {
                      "address": "${{ secrets.FRP_SERVER_ADDR }}",
                      "port": 443,
                      "users": [
                        {
                          "id": "${{ secrets.V2RAY_UUID }}",
                          "encryption": "none"
                        }
                      ]
                    }
                  ]
                },
                "streamSettings": {
                  "network": "ws",
                  "security": "tls",
                  "wsSettings": {
                    "path": "/ws-ngrok"
                  }
                }
              }
            ]
          }
          EOF

      - name: run xray
        run: |
          xray -config config.json &

      - name: setup key
        run: |
          echo "$SSH_KEY" > key
          chmod 600 key

      - name: reverse tunnel to your server
        run: |
          ssh -i key -o StrictHostKeyChecking=no \
          -R 1081:127.0.0.1:1080 ngrokuser@${{ secrets.FRP_SERVER_ADDR }}
